In [18]:
import numpy as np
from scipy import signal

In [6]:
image = np.array([[0.05, 0.59, 0.1 , 0.62, 0.74, 0.05, 0.3 ],
       [0.11, 0.46, 0.03, 0.62, 0.85, 0.55, 0.49],
       [0.46, 0.76, 0.65, 0.74, 0.37, 0.87, 0.12],
       [0.21, 0.62, 0.31, 0.56, 0.46, 0.46, 0.23],
       [0.87, 0.18, 0.27, 0.65, 0.45, 0.44, 0.4 ],
       [0.  , 0.83, 0.82, 0.59, 0.26, 0.46, 0.79],
       [0.5 , 0.48, 0.15, 0.42, 0.14, 0.69, 0.87]])
image

array([[0.05, 0.59, 0.1 , 0.62, 0.74, 0.05, 0.3 ],
       [0.11, 0.46, 0.03, 0.62, 0.85, 0.55, 0.49],
       [0.46, 0.76, 0.65, 0.74, 0.37, 0.87, 0.12],
       [0.21, 0.62, 0.31, 0.56, 0.46, 0.46, 0.23],
       [0.87, 0.18, 0.27, 0.65, 0.45, 0.44, 0.4 ],
       [0.  , 0.83, 0.82, 0.59, 0.26, 0.46, 0.79],
       [0.5 , 0.48, 0.15, 0.42, 0.14, 0.69, 0.87]])

In [16]:
high_pass_filter = np.array([[ 0.  , -0.25,  0.  ],
                             [-0.25,  2.  , -0.25],
                             [ 0.  , -0.25,  0.  ]])
high_pass_filter

array([[ 0.  , -0.25,  0.  ],
       [-0.25,  2.  , -0.25],
       [ 0.  , -0.25,  0.  ]])

In [24]:
res = np.around(signal.convolve2d(image, high_pass_filter, mode="valid"), decimals=2)
res

array([[ 0.55, -0.4 ,  0.68,  1.13,  0.54],
       [ 0.97,  0.84,  0.93,  0.01,  1.36],
       [ 0.88,  0.09,  0.58,  0.46,  0.42],
       [-0.29,  0.05,  0.83,  0.45,  0.44],
       [ 1.29,  1.18,  0.64,  0.11,  0.38]])